

version: '3.8'

services:
  webnode: 
    container_name: example
    restart: always
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    networks:
      - mynetwork
    volumes:
      - .:/usr/src/app

  mongo: 
    container_name: mongodb
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27676:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - mynetwork
   

volumes:
  mongo-data:

networks:
  mynetwork:
    driver: bridge
